apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drk00-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drk00
  template:
    metadata:
      labels:
        app: drk00
    spec:
      containers:
        - name: drk00-container
          image: localhost:5000/drk/node-web-app:latest
          imagePullPolicy: 'Always'
---
apiVersion: v1
kind: Service
metadata:
  name: drk00-service
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 80
  selector:
    app: drk00
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: drk00-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: drk00.localhost
      http:
        paths:
          - path: /
            backend:
              serviceName: drk00-service
              servicePort: 80
